version: "3.8"

services:
  # Frontend - Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - pawa-network
    restart: unless-stopped

  # Backend - Laravel
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
      - ./backend/storage:/var/www/storage
    env_file:
      - .env
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    networks:
      - pawa-network
    restart: unless-stopped

networks:
  pawa-network:
    driver: bridge
